name = "Bplus"
uuid = "c71c5366-3533-40c3-bcf3-6383cd1eb1eb"
authors = ["William Manning <manning.w27@gmail.com>"]
version = "0.1.0"

[deps]
BplusApp = "6498524c-785b-4e26-b825-b7be109d6de7"
BplusCore = "1fb136ff-715c-473e-9ae1-0caef0ff09b1"
BplusTools = "9c855568-ef52-4907-8d6a-2b3bbb89a4a6"

[compat]
julia = "1.9"
BplusCore="=0.1.0"
BplusApp="=0.1.0"
BplusTools="=0.1.0"