name = "Bplus"
uuid = "c71c5366-3533-40c3-bcf3-6383cd1eb1eb"
authors = ["William Manning <manning.w27@gmail.com>"]
version = "0.1.5"

[deps]
Assimp = "079381af-6941-5802-8ad5-fb13e7f1c93a"
BitFlags = "d1d4a3ce-64b1-5f1a-9ba4-7e7e69966f35"
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
CSyntax = "ea656a56-6ca6-5dda-bba5-7b6963a5f74c"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LibCImGui = "9be01004-c4f5-478b-abeb-cb32b114cf5e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
ModernGLbp = "2930cd1e-366e-4c08-992f-3bff68fce32f"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[compat]
CImGui = "=1.82.0"
LibCImGui = "=1.82.2"